import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ payload }: MigrateUpArgs): Promise<void> {
await payload.db.drizzle.execute(sql`

DROP INDEX IF EXISTS "er_media_sizes_128_sizes_128_filename_idx";
ALTER TABLE "fashion_media" ADD COLUMN "sizes_16_9_url" varchar;
ALTER TABLE "fashion_media" ADD COLUMN "sizes_16_9_width" numeric;
ALTER TABLE "fashion_media" ADD COLUMN "sizes_16_9_height" numeric;
ALTER TABLE "fashion_media" ADD COLUMN "sizes_16_9_mime_type" varchar;
ALTER TABLE "fashion_media" ADD COLUMN "sizes_16_9_filesize" numeric;
ALTER TABLE "fashion_media" ADD COLUMN "sizes_16_9_filename" varchar;
ALTER TABLE "fashion_media" ADD COLUMN "sizes_card_url" varchar;
ALTER TABLE "fashion_media" ADD COLUMN "sizes_card_width" numeric;
ALTER TABLE "fashion_media" ADD COLUMN "sizes_card_height" numeric;
ALTER TABLE "fashion_media" ADD COLUMN "sizes_card_mime_type" varchar;
ALTER TABLE "fashion_media" ADD COLUMN "sizes_card_filesize" numeric;
ALTER TABLE "fashion_media" ADD COLUMN "sizes_card_filename" varchar;
ALTER TABLE "media" ADD COLUMN "sizes_16_9_url" varchar;
ALTER TABLE "media" ADD COLUMN "sizes_16_9_width" numeric;
ALTER TABLE "media" ADD COLUMN "sizes_16_9_height" numeric;
ALTER TABLE "media" ADD COLUMN "sizes_16_9_mime_type" varchar;
ALTER TABLE "media" ADD COLUMN "sizes_16_9_filesize" numeric;
ALTER TABLE "media" ADD COLUMN "sizes_16_9_filename" varchar;
ALTER TABLE "media" ADD COLUMN "sizes_card_url" varchar;
ALTER TABLE "media" ADD COLUMN "sizes_card_width" numeric;
ALTER TABLE "media" ADD COLUMN "sizes_card_height" numeric;
ALTER TABLE "media" ADD COLUMN "sizes_card_mime_type" varchar;
ALTER TABLE "media" ADD COLUMN "sizes_card_filesize" numeric;
ALTER TABLE "media" ADD COLUMN "sizes_card_filename" varchar;
ALTER TABLE "media" ADD COLUMN "sizes_256_url" varchar;
ALTER TABLE "media" ADD COLUMN "sizes_256_width" numeric;
ALTER TABLE "media" ADD COLUMN "sizes_256_height" numeric;
ALTER TABLE "media" ADD COLUMN "sizes_256_mime_type" varchar;
ALTER TABLE "media" ADD COLUMN "sizes_256_filesize" numeric;
ALTER TABLE "media" ADD COLUMN "sizes_256_filename" varchar;
ALTER TABLE "media" ADD COLUMN "sizes_64_url" varchar;
ALTER TABLE "media" ADD COLUMN "sizes_64_width" numeric;
ALTER TABLE "media" ADD COLUMN "sizes_64_height" numeric;
ALTER TABLE "media" ADD COLUMN "sizes_64_mime_type" varchar;
ALTER TABLE "media" ADD COLUMN "sizes_64_filesize" numeric;
ALTER TABLE "media" ADD COLUMN "sizes_64_filename" varchar;
ALTER TABLE "sliders_media" ADD COLUMN "sizes_16_9_url" varchar;
ALTER TABLE "sliders_media" ADD COLUMN "sizes_16_9_width" numeric;
ALTER TABLE "sliders_media" ADD COLUMN "sizes_16_9_height" numeric;
ALTER TABLE "sliders_media" ADD COLUMN "sizes_16_9_mime_type" varchar;
ALTER TABLE "sliders_media" ADD COLUMN "sizes_16_9_filesize" numeric;
ALTER TABLE "sliders_media" ADD COLUMN "sizes_16_9_filename" varchar;
ALTER TABLE "sliders_media" ADD COLUMN "sizes_card_url" varchar;
ALTER TABLE "sliders_media" ADD COLUMN "sizes_card_width" numeric;
ALTER TABLE "sliders_media" ADD COLUMN "sizes_card_height" numeric;
ALTER TABLE "sliders_media" ADD COLUMN "sizes_card_mime_type" varchar;
ALTER TABLE "sliders_media" ADD COLUMN "sizes_card_filesize" numeric;
ALTER TABLE "sliders_media" ADD COLUMN "sizes_card_filename" varchar;
ALTER TABLE "er_media" ADD COLUMN "sizes_card_url" varchar;
ALTER TABLE "er_media" ADD COLUMN "sizes_card_width" numeric;
ALTER TABLE "er_media" ADD COLUMN "sizes_card_height" numeric;
ALTER TABLE "er_media" ADD COLUMN "sizes_card_mime_type" varchar;
ALTER TABLE "er_media" ADD COLUMN "sizes_card_filesize" numeric;
ALTER TABLE "er_media" ADD COLUMN "sizes_card_filename" varchar;
ALTER TABLE "er_media" ADD COLUMN "sizes_256_url" varchar;
ALTER TABLE "er_media" ADD COLUMN "sizes_256_width" numeric;
ALTER TABLE "er_media" ADD COLUMN "sizes_256_height" numeric;
ALTER TABLE "er_media" ADD COLUMN "sizes_256_mime_type" varchar;
ALTER TABLE "er_media" ADD COLUMN "sizes_256_filesize" numeric;
ALTER TABLE "er_media" ADD COLUMN "sizes_256_filename" varchar;
CREATE INDEX IF NOT EXISTS "fashion_media_sizes_16_9_sizes_16_9_filename_idx" ON "fashion_media" ("sizes_16_9_filename");
CREATE INDEX IF NOT EXISTS "fashion_media_sizes_card_sizes_card_filename_idx" ON "fashion_media" ("sizes_card_filename");
CREATE INDEX IF NOT EXISTS "media_sizes_16_9_sizes_16_9_filename_idx" ON "media" ("sizes_16_9_filename");
CREATE INDEX IF NOT EXISTS "media_sizes_card_sizes_card_filename_idx" ON "media" ("sizes_card_filename");
CREATE INDEX IF NOT EXISTS "media_sizes_256_sizes_256_filename_idx" ON "media" ("sizes_256_filename");
CREATE INDEX IF NOT EXISTS "media_sizes_64_sizes_64_filename_idx" ON "media" ("sizes_64_filename");
CREATE INDEX IF NOT EXISTS "sliders_media_sizes_16_9_sizes_16_9_filename_idx" ON "sliders_media" ("sizes_16_9_filename");
CREATE INDEX IF NOT EXISTS "sliders_media_sizes_card_sizes_card_filename_idx" ON "sliders_media" ("sizes_card_filename");
CREATE INDEX IF NOT EXISTS "er_media_sizes_card_sizes_card_filename_idx" ON "er_media" ("sizes_card_filename");
CREATE INDEX IF NOT EXISTS "er_media_sizes_256_sizes_256_filename_idx" ON "er_media" ("sizes_256_filename");
ALTER TABLE "fashion_media" DROP COLUMN IF EXISTS "prefix";
ALTER TABLE "media" DROP COLUMN IF EXISTS "prefix";
ALTER TABLE "sliders_media" DROP COLUMN IF EXISTS "prefix";
ALTER TABLE "er_media" DROP COLUMN IF EXISTS "prefix";
ALTER TABLE "er_media" DROP COLUMN IF EXISTS "sizes_128_url";
ALTER TABLE "er_media" DROP COLUMN IF EXISTS "sizes_128_width";
ALTER TABLE "er_media" DROP COLUMN IF EXISTS "sizes_128_height";
ALTER TABLE "er_media" DROP COLUMN IF EXISTS "sizes_128_mime_type";
ALTER TABLE "er_media" DROP COLUMN IF EXISTS "sizes_128_filesize";
ALTER TABLE "er_media" DROP COLUMN IF EXISTS "sizes_128_filename";`);

};

export async function down({ payload }: MigrateDownArgs): Promise<void> {
await payload.db.drizzle.execute(sql`

DROP INDEX IF EXISTS "fashion_media_sizes_16_9_sizes_16_9_filename_idx";
DROP INDEX IF EXISTS "fashion_media_sizes_card_sizes_card_filename_idx";
DROP INDEX IF EXISTS "media_sizes_16_9_sizes_16_9_filename_idx";
DROP INDEX IF EXISTS "media_sizes_card_sizes_card_filename_idx";
DROP INDEX IF EXISTS "media_sizes_256_sizes_256_filename_idx";
DROP INDEX IF EXISTS "media_sizes_64_sizes_64_filename_idx";
DROP INDEX IF EXISTS "sliders_media_sizes_16_9_sizes_16_9_filename_idx";
DROP INDEX IF EXISTS "sliders_media_sizes_card_sizes_card_filename_idx";
DROP INDEX IF EXISTS "er_media_sizes_card_sizes_card_filename_idx";
DROP INDEX IF EXISTS "er_media_sizes_256_sizes_256_filename_idx";
ALTER TABLE "fashion_media" ADD COLUMN "prefix" varchar;
ALTER TABLE "media" ADD COLUMN "prefix" varchar;
ALTER TABLE "sliders_media" ADD COLUMN "prefix" varchar;
ALTER TABLE "er_media" ADD COLUMN "prefix" varchar;
ALTER TABLE "er_media" ADD COLUMN "sizes_128_url" varchar;
ALTER TABLE "er_media" ADD COLUMN "sizes_128_width" numeric;
ALTER TABLE "er_media" ADD COLUMN "sizes_128_height" numeric;
ALTER TABLE "er_media" ADD COLUMN "sizes_128_mime_type" varchar;
ALTER TABLE "er_media" ADD COLUMN "sizes_128_filesize" numeric;
ALTER TABLE "er_media" ADD COLUMN "sizes_128_filename" varchar;
CREATE INDEX IF NOT EXISTS "er_media_sizes_128_sizes_128_filename_idx" ON "er_media" ("sizes_128_filename");
ALTER TABLE "fashion_media" DROP COLUMN IF EXISTS "sizes_16_9_url";
ALTER TABLE "fashion_media" DROP COLUMN IF EXISTS "sizes_16_9_width";
ALTER TABLE "fashion_media" DROP COLUMN IF EXISTS "sizes_16_9_height";
ALTER TABLE "fashion_media" DROP COLUMN IF EXISTS "sizes_16_9_mime_type";
ALTER TABLE "fashion_media" DROP COLUMN IF EXISTS "sizes_16_9_filesize";
ALTER TABLE "fashion_media" DROP COLUMN IF EXISTS "sizes_16_9_filename";
ALTER TABLE "fashion_media" DROP COLUMN IF EXISTS "sizes_card_url";
ALTER TABLE "fashion_media" DROP COLUMN IF EXISTS "sizes_card_width";
ALTER TABLE "fashion_media" DROP COLUMN IF EXISTS "sizes_card_height";
ALTER TABLE "fashion_media" DROP COLUMN IF EXISTS "sizes_card_mime_type";
ALTER TABLE "fashion_media" DROP COLUMN IF EXISTS "sizes_card_filesize";
ALTER TABLE "fashion_media" DROP COLUMN IF EXISTS "sizes_card_filename";
ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_16_9_url";
ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_16_9_width";
ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_16_9_height";
ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_16_9_mime_type";
ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_16_9_filesize";
ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_16_9_filename";
ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_card_url";
ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_card_width";
ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_card_height";
ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_card_mime_type";
ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_card_filesize";
ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_card_filename";
ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_256_url";
ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_256_width";
ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_256_height";
ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_256_mime_type";
ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_256_filesize";
ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_256_filename";
ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_64_url";
ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_64_width";
ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_64_height";
ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_64_mime_type";
ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_64_filesize";
ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_64_filename";
ALTER TABLE "sliders_media" DROP COLUMN IF EXISTS "sizes_16_9_url";
ALTER TABLE "sliders_media" DROP COLUMN IF EXISTS "sizes_16_9_width";
ALTER TABLE "sliders_media" DROP COLUMN IF EXISTS "sizes_16_9_height";
ALTER TABLE "sliders_media" DROP COLUMN IF EXISTS "sizes_16_9_mime_type";
ALTER TABLE "sliders_media" DROP COLUMN IF EXISTS "sizes_16_9_filesize";
ALTER TABLE "sliders_media" DROP COLUMN IF EXISTS "sizes_16_9_filename";
ALTER TABLE "sliders_media" DROP COLUMN IF EXISTS "sizes_card_url";
ALTER TABLE "sliders_media" DROP COLUMN IF EXISTS "sizes_card_width";
ALTER TABLE "sliders_media" DROP COLUMN IF EXISTS "sizes_card_height";
ALTER TABLE "sliders_media" DROP COLUMN IF EXISTS "sizes_card_mime_type";
ALTER TABLE "sliders_media" DROP COLUMN IF EXISTS "sizes_card_filesize";
ALTER TABLE "sliders_media" DROP COLUMN IF EXISTS "sizes_card_filename";
ALTER TABLE "er_media" DROP COLUMN IF EXISTS "sizes_card_url";
ALTER TABLE "er_media" DROP COLUMN IF EXISTS "sizes_card_width";
ALTER TABLE "er_media" DROP COLUMN IF EXISTS "sizes_card_height";
ALTER TABLE "er_media" DROP COLUMN IF EXISTS "sizes_card_mime_type";
ALTER TABLE "er_media" DROP COLUMN IF EXISTS "sizes_card_filesize";
ALTER TABLE "er_media" DROP COLUMN IF EXISTS "sizes_card_filename";
ALTER TABLE "er_media" DROP COLUMN IF EXISTS "sizes_256_url";
ALTER TABLE "er_media" DROP COLUMN IF EXISTS "sizes_256_width";
ALTER TABLE "er_media" DROP COLUMN IF EXISTS "sizes_256_height";
ALTER TABLE "er_media" DROP COLUMN IF EXISTS "sizes_256_mime_type";
ALTER TABLE "er_media" DROP COLUMN IF EXISTS "sizes_256_filesize";
ALTER TABLE "er_media" DROP COLUMN IF EXISTS "sizes_256_filename";`);

};
