/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    users: User;
    archetypes: Archetype;
    restrictions: Restriction;
    'er-ashes-of-war': ErAshesOfWar;
    'er-builds': ErBuild;
    'er-classes': ErClass;
    'er-skills': ErSkill;
    'er-statistics': ErStatistic;
    'er-weapon-types': ErWeaponType;
    'er-weapons': ErWeapon;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  globals: {};
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "archetypes".
 */
export interface Archetype {
  id: number;
  name?: string | null;
  description?:
    | {
        [k: string]: unknown;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "restrictions".
 */
export interface Restriction {
  id: number;
  name?: string | null;
  description?:
    | {
        [k: string]: unknown;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "er-ashes-of-war".
 */
export interface ErAshesOfWar {
  id: number;
  name?: string | null;
  skill?: (number | null) | ErSkill;
  description?:
    | {
        [k: string]: unknown;
      }[]
    | null;
  location?:
    | {
        [k: string]: unknown;
      }[]
    | null;
  availability?: (number | ErWeaponType)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "er-skills".
 */
export interface ErSkill {
  id: number;
  name?: string | null;
  fp_cost?: number | null;
  description?:
    | {
        [k: string]: unknown;
      }[]
    | null;
  location?:
    | {
        [k: string]: unknown;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "er-weapon-types".
 */
export interface ErWeaponType {
  id: number;
  name?: string | null;
  description?:
    | {
        [k: string]: unknown;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "er-builds".
 */
export interface ErBuild {
  id: number;
  name?: string | null;
  description?:
    | {
        [k: string]: unknown;
      }[]
    | null;
  youtube_url?: string | null;
  restrictions?: (number | Restriction)[] | null;
  archetype?: (number | null) | Archetype;
  is_two_handed?: boolean | null;
  mainhand_weapons?:
    | {
        weapon?: (number | null) | ErWeapon;
        ash_of_war?: (number | null) | ErAshesOfWar;
        id?: string | null;
      }[]
    | null;
  offhand_weapons?:
    | {
        weapon?: (number | null) | ErWeapon;
        ash_of_war?: (number | null) | ErAshesOfWar;
        id?: string | null;
      }[]
    | null;
  starting_class?: (number | null) | ErClass;
  statistics?:
    | {
        stat?: (number | null) | ErStatistic;
        value?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "er-weapons".
 */
export interface ErWeapon {
  id: number;
  weapon_type?: (number | null) | ErWeaponType;
  skill?: (number | null) | ErSkill;
  name?: string | null;
  description?:
    | {
        [k: string]: unknown;
      }[]
    | null;
  weight?: number | null;
  attack?: {
    physical?: number | null;
    magic?: number | null;
    fire?: number | null;
    lightning?: number | null;
    holy?: number | null;
    critical?: number | null;
  };
  defense?: {
    physical?: number | null;
    magic?: number | null;
    fire?: number | null;
    lightning?: number | null;
    holy?: number | null;
    boost?: number | null;
  };
  scaling?:
    | {
        statistic: number | ErStatistic;
        letter: 'S' | 'A' | 'B' | 'C' | 'D' | 'E' | 'TODO';
        id?: string | null;
      }[]
    | null;
  requirements?:
    | {
        statistic: number | ErStatistic;
        value: number;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "er-statistics".
 */
export interface ErStatistic {
  id: number;
  name?: string | null;
  description?:
    | {
        [k: string]: unknown;
      }[]
    | null;
  softcaps?:
    | {
        level?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "er-classes".
 */
export interface ErClass {
  id: number;
  name?: string | null;
  weapons?: (number | ErWeapon)[] | null;
  statistics?:
    | {
        stat?: (number | null) | ErStatistic;
        value?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}